name: Build LaTeX Document

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Compile LaTeX document
      uses: dante-ev/latex-action@latest
      with:
        root_file: document.tex
        compiler: pdflatex
        args: -interaction=nonstopmode

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v3
      with:
        name: compiled-document
        path: document.pdf

    # - name: Create Git Tag
    #   id: tag
    #   env:
    #     TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    #   run: |
    #     TAG_NAME="release-$(date +'%Y%m%d%H%M%S')"
    #     echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
    #     git config --global user.name "github-actions[bot]"
    #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
    #     git tag $TAG_NAME
    #     git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} $TAG_NAME

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: document.pdf
        # tag_name: ${{ env.TAG_NAME }}
        tag_name: ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
